# Generated by Django 5.1.3 on 2025-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0002_item_ancho_hoja"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="alto_lama",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
