# Generated by Django 5.1.3 on 2025-01-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0003_item_alto_lama"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="insumo",
            name="tipo_insumo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="presupuestos.tipoinsumo",
            ),
        ),
    ]
