# Generated by Django 5.1.3 on 2025-01-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0004_tipoinsumo_insumo_tipo_insumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="mosquitero",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="detalleinsumo",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="presupuestos.item",
            ),
        ),
        migrations.AlterField(
            model_name="detalleinsumo",
            name="presupuesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="presupuestos.presupuesto",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="alto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ancho",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
