# Generated by Django 5.1.3 on 2025-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0005_item_mosquitero_alter_detalleinsumo_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PorcentajeConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre identificativo de esta configuración",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "mano_obra_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Porcentaje de mano de obra (ej: 40 = 40%)",
                        max_digits=5,
                    ),
                ),
                (
                    "venta_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        help_text="Porcentaje de venta (ej: 30 = 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "utilidad_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=85,
                        help_text="Porcentaje de utilidad (ej: 85 = 85%)",
                        max_digits=5,
                    ),
                ),
                (
                    "flete_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=12,
                        help_text="Porcentaje de flete (ej: 12 = 12%)",
                        max_digits=5,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta es la configuración activa",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuraión de Porcentajes",
                "verbose_name_plural": "Configuraciones de Porcentajes",
            },
        ),
    ]
