# Generated by Django 5.1.3 on 2026-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0006_add_porcentaje_configuracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleinsumo",
            name="cantidad_usada",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="detalleinsumo",
            name="precio_total",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
