# Generated by Django 6.1 on 2026-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_alter_detalleinsumo_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nombre_item',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
